Use `Object.assign` instead of `assign` from `@ember/polyfills`
ember-cli/ember-ajax pull request #463
Opened 2022-02-15 10:58 UTC by boris-petrov

Because the latter is deprecated in Ember 4.

cc @Turbo87

2022-03-07 08:03 UTC, boris-petrov commented
Ping @Turbo87. :)

2022-05-23 14:48 UTC, Turbo87 commented
I'm no longer on the ember-cli team, I'm not maintaining this addon and I'm not even using it anymore. Feel free to ping the ember-cli team though 🤷‍♂️

2022-09-29 09:56 UTC, rmachielse commented
@mike-north @rwjblue anyone who can merge/release this trivial change?

2022-10-10 18:50 UTC, bertdeblock commented
Updated the PR to use the spread syntax for `/addon` code, so we don't have to do a major.

2022-10-11 15:47 UTC, chriskrycho requested changes
Confirmed spread should be safe for 🔥 DIAF IE11 🔥 ([noisy, but safe](https://babeljs.io/repl#?browsers=ie%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=DYUwLgBAHhC8EG8IDpVIO4EMwC4JgCcBXECAX3IG4g&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.19.5&externalPlugins=&assumptions=%7B%7D)).

But it looks like we missed a couple (albeit just in test code)!

2022-10-11 16:29 UTC, chriskrycho commented on tests/helpers/start-app.js
> +  let attributes = Object.assign({}, config.APP);
Nah, as @bertdeblock pointed out in Discord, these don't run in IE.

2022-10-11 16:29 UTC, chriskrycho approved these changes

2022-10-11 16:45 UTC, merged

2022-10-11 18:29 UTC, bertdeblock commented
Published as `v5.1.2`. Thanks for doing the work @boris-petrov.

2022-10-11 18:56 UTC, boris-petrov commented
Thank *you* for taking it all the way to a release!